- name: pre-install
  stat:
    path: /etc/mysql/.autobiz.mariadb
  register: test_file

- name: set up .my.cnf file
  template:
    src: "root/my.cnf.j2"
    dest: "~/.my.cnf"
    owner: root
    group: root
    mode: 0600

- name: change mariadb root password
  mysql_user:
    name: "{{ mysql_root_username }}"
    host: "{{ item }}"
    password: "{{mysql_root_password }}"
    check_implicit_admin: "yes"
    priv: "*.*:ALL,GRANT"
  with_items: "{{ mysql_hosts }}"
  when: test_file.stat.exists == false

- file:
    path: /etc/mysql/.autobiz.mariadb
    state: '{{ "file" if  test_file.stat.exists else "touch"}}'
    owner: root
    group: root
    mode: 0640

    #- name: Remove anonymous MySQL users
    # mysql_user:
    #name: 'debian-sys-maint'
    #host_all: true
    #state: absent
    #login_user: '{{ mysql_root_username }}'
    #login_password: '{{ mysql_root_password }}'

- name: Remove MySQL test database
  mysql_db:
    name: test
    state: absent
    login_user: '{{ mysql_root_username }}'
    login_password: '{{ mysql_root_password }}'
